# Generated by Django 5.2.11 on 2026-02-14 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2026, validators=[django.core.validators.MaxValueValidator(2026), django.core.validators.MinValueValidator(2015)]),
        ),
    ]
